# Generated by Django 3.1.5 on 2021-02-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(default='', max_length=200)),
                ('side', models.CharField(default='', max_length=200)),
                ('qty', models.IntegerField(default='')),
                ('symbol', models.CharField(default='', max_length=200)),
                ('px', models.IntegerField(default='')),
                ('exchange', models.CharField(default='', max_length=200)),
                ('class_type', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('tags', models.CharField(default='', max_length=200)),
                ('local_time', models.CharField(default='', max_length=200)),
                ('source', models.CharField(default='', max_length=200)),
                ('orderID', models.CharField(default='', max_length=200)),
                ('exchangeOID', models.CharField(default='', max_length=200)),
                ('fillID', models.CharField(default='', max_length=200)),
                ('strategy', models.CharField(default='', max_length=200)),
                ('ilink', models.CharField(default='', max_length=200)),
                ('px_multiplier', models.CharField(default='', max_length=200)),
                ('multiplier', models.CharField(default='', max_length=200)),
                ('TO', models.CharField(default='', max_length=200)),
                ('OC', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
